name: phamarcy_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  universal_platform: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7
  dartx: ^1.2.0
  fl_chart: ^1.0.0
  flutter_bloc: ^8.1.6
  package_info_plus: ^8.0.2
  equatable: ^2.0.5
  intl: ^0.20.1
  device_preview: ^1.2.0
  mysql_client: ^0.0.27
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pharmacy_logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
    - family: playwrite
      fonts:
        - asset: assets/fonts/Playwrite.ttf
